// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass SettingContainer : Microsoft.UI.Xaml.Controls.ContentControl
    {
        SettingContainer();

        IInspectable Header;
        static Microsoft.UI.Xaml.DependencyProperty HeaderProperty { get; };

        String HelpText;
        static Microsoft.UI.Xaml.DependencyProperty HelpTextProperty { get; };

        String CurrentValue;
        static Microsoft.UI.Xaml.DependencyProperty CurrentValueProperty { get; };

        Boolean HasSettingValue;
        static Microsoft.UI.Xaml.DependencyProperty HasSettingValueProperty { get; };

        IInspectable SettingOverrideSource;
        static Microsoft.UI.Xaml.DependencyProperty SettingOverrideSourceProperty { get; };

        event Windows.Foundation.TypedEventHandler<SettingContainer, Object> ClearSettingValue;
    };
}
