// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "HighlightedText.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass HighlightedTextControl : Microsoft.UI.Xaml.Controls.Control
    {
        HighlightedTextControl();
        Microsoft.UI.Xaml.DependencyProperty TextProperty { get; };
        HighlightedText Text;
        Microsoft.UI.Xaml.Controls.TextBlock TextView { get; };    
    }
}
