// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass PaletteItemTemplateSelector : Microsoft.UI.Xaml.Controls.DataTemplateSelector
    {
        PaletteItemTemplateSelector();

        Microsoft.UI.Xaml.DataTemplate TabItemTemplate;
        Microsoft.UI.Xaml.DataTemplate NestedItemTemplate;
        Microsoft.UI.Xaml.DataTemplate GeneralItemTemplate;
    }
}
