// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass TabRowControl : Microsoft.UI.Xaml.Controls.ContentPresenter,
                                                     Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        TabRowControl();
        Microsoft.UI.Xaml.Controls.TabView TabView { get; };
        Boolean ShowElevationShield;
    }
}
